version: '3.8'

services:
  backend:
    build: ./BMICalculator
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./BMICalculator:/app
      - templates:/app/build
    depends_on:
      - frontend
  
  frontend:
    build: ./bmicalculator-frontend
    ports:
      - 3000:3000
    volumes:
      - ./bmicalculator-frontend:/app
      - templates:/app/build
volumes:
  templates: